__Attacker's goal__
  - method which in order to be viable
    + (high) requires this condition to be true
    + and this condition which depends on either
      - x to be true
      - or y to be true
    + hey this condition must be true too
    + [ ] but this would mitigate the problem
  - another method here too
    - a condition which depends on assumptions
      +? this might be a problem
        + [x] but this prevents it from being one
      +? but only if this happens
        -? which assumes this also happens

